// lib/countries.ts
// Liste complète des pays avec indicatifs téléphoniques, drapeaux emoji et nombre de chiffres attendus

export interface CountryInfo {
    code: string;   // Indicatif téléphonique (ex: '+33')
    flag: string;   // Emoji drapeau
    name: string;   // Nom du pays en français
    digits: number; // Nombre de chiffres du numéro national (sans indicatif)
    iso?: string;   // Code pays sur 2 lettres (ex: 'fr') généré automatiquement
}

export const COUNTRIES: CountryInfo[] = [
    // ── Afrique ──────────────────────────────────────
    { code: '+213', flag: '🇩🇿', name: 'Algérie', digits: 9 },
    { code: '+244', flag: '🇦🇴', name: 'Angola', digits: 9 },
    { code: '+229', flag: '🇧🇯', name: 'Bénin', digits: 8 },
    { code: '+267', flag: '🇧🇼', name: 'Botswana', digits: 8 },
    { code: '+226', flag: '🇧🇫', name: 'Burkina Faso', digits: 8 },
    { code: '+257', flag: '🇧🇮', name: 'Burundi', digits: 8 },
    { code: '+237', flag: '🇨🇲', name: 'Cameroun', digits: 9 },
    { code: '+238', flag: '🇨🇻', name: 'Cap-Vert', digits: 7 },
    { code: '+236', flag: '🇨🇫', name: 'Centrafrique', digits: 8 },
    { code: '+269', flag: '🇰🇲', name: 'Comores', digits: 7 },
    { code: '+242', flag: '🇨🇬', name: 'Congo', digits: 9 },
    { code: '+243', flag: '🇨🇩', name: 'RD Congo', digits: 9 },
    { code: '+225', flag: '🇨🇮', name: "Côte d'Ivoire", digits: 10 },
    { code: '+253', flag: '🇩🇯', name: 'Djibouti', digits: 8 },
    { code: '+20', flag: '🇪🇬', name: 'Égypte', digits: 10 },
    { code: '+291', flag: '🇪🇷', name: 'Érythrée', digits: 7 },
    { code: '+268', flag: '🇸🇿', name: 'Eswatini', digits: 8 },
    { code: '+251', flag: '🇪🇹', name: 'Éthiopie', digits: 9 },
    { code: '+241', flag: '🇬🇦', name: 'Gabon', digits: 7 },
    { code: '+220', flag: '🇬🇲', name: 'Gambie', digits: 7 },
    { code: '+233', flag: '🇬🇭', name: 'Ghana', digits: 9 },
    { code: '+224', flag: '🇬🇳', name: 'Guinée', digits: 9 },
    { code: '+245', flag: '🇬🇼', name: 'Guinée-Bissau', digits: 7 },
    { code: '+240', flag: '🇬🇶', name: 'Guinée équatoriale', digits: 9 },
    { code: '+254', flag: '🇰🇪', name: 'Kenya', digits: 10 },
    { code: '+266', flag: '🇱🇸', name: 'Lesotho', digits: 8 },
    { code: '+231', flag: '🇱🇷', name: 'Libéria', digits: 9 },
    { code: '+218', flag: '🇱🇾', name: 'Libye', digits: 10 },
    { code: '+261', flag: '🇲🇬', name: 'Madagascar', digits: 9 },
    { code: '+265', flag: '🇲🇼', name: 'Malawi', digits: 9 },
    { code: '+223', flag: '🇲🇱', name: 'Mali', digits: 8 },
    { code: '+212', flag: '🇲🇦', name: 'Maroc', digits: 9 },
    { code: '+230', flag: '🇲🇺', name: 'Maurice', digits: 8 },
    { code: '+222', flag: '🇲🇷', name: 'Mauritanie', digits: 8 },
    { code: '+258', flag: '🇲🇿', name: 'Mozambique', digits: 9 },
    { code: '+264', flag: '🇳🇦', name: 'Namibie', digits: 10 },
    { code: '+227', flag: '🇳🇪', name: 'Niger', digits: 8 },
    { code: '+234', flag: '🇳🇬', name: 'Nigéria', digits: 10 },
    { code: '+256', flag: '🇺🇬', name: 'Ouganda', digits: 9 },
    { code: '+250', flag: '🇷🇼', name: 'Rwanda', digits: 9 },
    { code: '+239', flag: '🇸🇹', name: 'São Tomé-et-Príncipe', digits: 7 },
    { code: '+221', flag: '🇸🇳', name: 'Sénégal', digits: 9 },
    { code: '+248', flag: '🇸🇨', name: 'Seychelles', digits: 7 },
    { code: '+232', flag: '🇸🇱', name: 'Sierra Leone', digits: 8 },
    { code: '+252', flag: '🇸🇴', name: 'Somalie', digits: 8 },
    { code: '+249', flag: '🇸🇩', name: 'Soudan', digits: 9 },
    { code: '+211', flag: '🇸🇸', name: 'Soudan du Sud', digits: 9 },
    { code: '+255', flag: '🇹🇿', name: 'Tanzanie', digits: 9 },
    { code: '+235', flag: '🇹🇩', name: 'Tchad', digits: 8 },
    { code: '+228', flag: '🇹🇬', name: 'Togo', digits: 8 },
    { code: '+216', flag: '🇹🇳', name: 'Tunisie', digits: 8 },
    { code: '+260', flag: '🇿🇲', name: 'Zambie', digits: 9 },
    { code: '+263', flag: '🇿🇼', name: 'Zimbabwe', digits: 9 },
    { code: '+27', flag: '🇿🇦', name: 'Afrique du Sud', digits: 9 },

    // ── Europe ───────────────────────────────────────
    { code: '+49', flag: '🇩🇪', name: 'Allemagne', digits: 11 },
    { code: '+43', flag: '🇦🇹', name: 'Autriche', digits: 10 },
    { code: '+32', flag: '🇧🇪', name: 'Belgique', digits: 9 },
    { code: '+375', flag: '🇧🇾', name: 'Biélorussie', digits: 10 },
    { code: '+387', flag: '🇧🇦', name: 'Bosnie-Herzégovine', digits: 8 },
    { code: '+359', flag: '🇧🇬', name: 'Bulgarie', digits: 9 },
    { code: '+385', flag: '🇭🇷', name: 'Croatie', digits: 9 },
    { code: '+45', flag: '🇩🇰', name: 'Danemark', digits: 8 },
    { code: '+34', flag: '🇪🇸', name: 'Espagne', digits: 9 },
    { code: '+372', flag: '🇪🇪', name: 'Estonie', digits: 8 },
    { code: '+358', flag: '🇫🇮', name: 'Finlande', digits: 9 },
    { code: '+33', flag: '🇫🇷', name: 'France', digits: 9 },
    { code: '+30', flag: '🇬🇷', name: 'Grèce', digits: 10 },
    { code: '+36', flag: '🇭🇺', name: 'Hongrie', digits: 9 },
    { code: '+353', flag: '🇮🇪', name: 'Irlande', digits: 9 },
    { code: '+354', flag: '🇮🇸', name: 'Islande', digits: 7 },
    { code: '+39', flag: '🇮🇹', name: 'Italie', digits: 10 },
    { code: '+371', flag: '🇱🇻', name: 'Lettonie', digits: 8 },
    { code: '+370', flag: '🇱🇹', name: 'Lituanie', digits: 8 },
    { code: '+352', flag: '🇱🇺', name: 'Luxembourg', digits: 9 },
    { code: '+389', flag: '🇲🇰', name: 'Macédoine du Nord', digits: 8 },
    { code: '+356', flag: '🇲🇹', name: 'Malte', digits: 8 },
    { code: '+373', flag: '🇲🇩', name: 'Moldavie', digits: 8 },
    { code: '+377', flag: '🇲🇨', name: 'Monaco', digits: 8 },
    { code: '+382', flag: '🇲🇪', name: 'Monténégro', digits: 8 },
    { code: '+47', flag: '🇳🇴', name: 'Norvège', digits: 8 },
    { code: '+31', flag: '🇳🇱', name: 'Pays-Bas', digits: 9 },
    { code: '+48', flag: '🇵🇱', name: 'Pologne', digits: 9 },
    { code: '+351', flag: '🇵🇹', name: 'Portugal', digits: 9 },
    { code: '+40', flag: '🇷🇴', name: 'Roumanie', digits: 10 },
    { code: '+44', flag: '🇬🇧', name: 'Royaume-Uni', digits: 10 },
    { code: '+7', flag: '🇷🇺', name: 'Russie', digits: 10 },
    { code: '+381', flag: '🇷🇸', name: 'Serbie', digits: 9 },
    { code: '+421', flag: '🇸🇰', name: 'Slovaquie', digits: 9 },
    { code: '+386', flag: '🇸🇮', name: 'Slovénie', digits: 8 },
    { code: '+46', flag: '🇸🇪', name: 'Suède', digits: 10 },
    { code: '+41', flag: '🇨🇭', name: 'Suisse', digits: 9 },
    { code: '+420', flag: '🇨🇿', name: 'Tchéquie', digits: 9 },
    { code: '+380', flag: '🇺🇦', name: 'Ukraine', digits: 9 },

    // ── Amériques ────────────────────────────────────
    { code: '+54', flag: '🇦🇷', name: 'Argentine', digits: 10 },
    { code: '+55', flag: '🇧🇷', name: 'Brésil', digits: 11 },
    { code: '+1', flag: '🇨🇦', name: 'Canada', digits: 10 },
    { code: '+56', flag: '🇨🇱', name: 'Chili', digits: 9 },
    { code: '+57', flag: '🇨🇴', name: 'Colombie', digits: 10 },
    { code: '+506', flag: '🇨🇷', name: 'Costa Rica', digits: 8 },
    { code: '+53', flag: '🇨🇺', name: 'Cuba', digits: 8 },
    { code: '+593', flag: '🇪🇨', name: 'Équateur', digits: 9 },
    { code: '+1', flag: '🇺🇸', name: 'États-Unis', digits: 10 },
    { code: '+502', flag: '🇬🇹', name: 'Guatemala', digits: 8 },
    { code: '+509', flag: '🇭🇹', name: 'Haïti', digits: 8 },
    { code: '+504', flag: '🇭🇳', name: 'Honduras', digits: 8 },
    { code: '+1', flag: '🇯🇲', name: 'Jamaïque', digits: 10 },
    { code: '+52', flag: '🇲🇽', name: 'Mexique', digits: 10 },
    { code: '+507', flag: '🇵🇦', name: 'Panama', digits: 8 },
    { code: '+595', flag: '🇵🇾', name: 'Paraguay', digits: 9 },
    { code: '+51', flag: '🇵🇪', name: 'Pérou', digits: 9 },
    { code: '+1', flag: '🇩🇴', name: 'Rép. Dominicaine', digits: 10 },
    { code: '+598', flag: '🇺🇾', name: 'Uruguay', digits: 8 },
    { code: '+58', flag: '🇻🇪', name: 'Venezuela', digits: 10 },

    // ── Asie ─────────────────────────────────────────
    { code: '+93', flag: '🇦🇫', name: 'Afghanistan', digits: 9 },
    { code: '+966', flag: '🇸🇦', name: 'Arabie Saoudite', digits: 9 },
    { code: '+374', flag: '🇦🇲', name: 'Arménie', digits: 8 },
    { code: '+994', flag: '🇦🇿', name: 'Azerbaïdjan', digits: 9 },
    { code: '+880', flag: '🇧🇩', name: 'Bangladesh', digits: 10 },
    { code: '+855', flag: '🇰🇭', name: 'Cambodge', digits: 9 },
    { code: '+86', flag: '🇨🇳', name: 'Chine', digits: 11 },
    { code: '+82', flag: '🇰🇷', name: 'Corée du Sud', digits: 10 },
    { code: '+971', flag: '🇦🇪', name: 'Émirats Arabes Unis', digits: 9 },
    { code: '+995', flag: '🇬🇪', name: 'Géorgie', digits: 9 },
    { code: '+91', flag: '🇮🇳', name: 'Inde', digits: 10 },
    { code: '+62', flag: '🇮🇩', name: 'Indonésie', digits: 10 },
    { code: '+98', flag: '🇮🇷', name: 'Iran', digits: 10 },
    { code: '+964', flag: '🇮🇶', name: 'Irak', digits: 10 },
    { code: '+972', flag: '🇮🇱', name: 'Israël', digits: 9 },
    { code: '+81', flag: '🇯🇵', name: 'Japon', digits: 10 },
    { code: '+962', flag: '🇯🇴', name: 'Jordanie', digits: 9 },
    { code: '+7', flag: '🇰🇿', name: 'Kazakhstan', digits: 10 },
    { code: '+965', flag: '🇰🇼', name: 'Koweït', digits: 8 },
    { code: '+856', flag: '🇱🇦', name: 'Laos', digits: 10 },
    { code: '+961', flag: '🇱🇧', name: 'Liban', digits: 8 },
    { code: '+60', flag: '🇲🇾', name: 'Malaisie', digits: 10 },
    { code: '+976', flag: '🇲🇳', name: 'Mongolie', digits: 8 },
    { code: '+95', flag: '🇲🇲', name: 'Myanmar', digits: 9 },
    { code: '+977', flag: '🇳🇵', name: 'Népal', digits: 10 },
    { code: '+968', flag: '🇴🇲', name: 'Oman', digits: 8 },
    { code: '+998', flag: '🇺🇿', name: 'Ouzbékistan', digits: 9 },
    { code: '+92', flag: '🇵🇰', name: 'Pakistan', digits: 10 },
    { code: '+63', flag: '🇵🇭', name: 'Philippines', digits: 10 },
    { code: '+974', flag: '🇶🇦', name: 'Qatar', digits: 8 },
    { code: '+94', flag: '🇱🇰', name: 'Sri Lanka', digits: 9 },
    { code: '+963', flag: '🇸🇾', name: 'Syrie', digits: 9 },
    { code: '+886', flag: '🇹🇼', name: 'Taïwan', digits: 9 },
    { code: '+992', flag: '🇹🇯', name: 'Tadjikistan', digits: 9 },
    { code: '+66', flag: '🇹🇭', name: 'Thaïlande', digits: 9 },
    { code: '+90', flag: '🇹🇷', name: 'Turquie', digits: 10 },
    { code: '+993', flag: '🇹🇲', name: 'Turkménistan', digits: 8 },
    { code: '+84', flag: '🇻🇳', name: 'Vietnam', digits: 9 },
    { code: '+967', flag: '🇾🇪', name: 'Yémen', digits: 9 },

    // ── Océanie ──────────────────────────────────────
    { code: '+61', flag: '🇦🇺', name: 'Australie', digits: 9 },
    { code: '+64', flag: '🇳🇿', name: 'Nouvelle-Zélande', digits: 9 },
    { code: '+675', flag: '🇵🇬', name: 'Papouasie-Nlle-Guinée', digits: 8 },

    // ── DOM-TOM Français ─────────────────────────────
    { code: '+590', flag: '🇬🇵', name: 'Guadeloupe', digits: 9 },
    { code: '+594', flag: '🇬🇫', name: 'Guyane française', digits: 9 },
    { code: '+596', flag: '🇲🇶', name: 'Martinique', digits: 9 },
    { code: '+262', flag: '🇷🇪', name: 'La Réunion', digits: 9 },
    { code: '+262', flag: '🇾🇹', name: 'Mayotte', digits: 9 },
    { code: '+687', flag: '🇳🇨', name: 'Nouvelle-Calédonie', digits: 6 },
    { code: '+689', flag: '🇵🇫', name: 'Polynésie française', digits: 6 },
];

export const SORTED_COUNTRIES: CountryInfo[] = COUNTRIES.map(c => {
    // Calculer le code ISO à partir des symboles indicateurs régionaux de l'emoji
    const iso = Array.from(c.flag)
        .map(char => String.fromCharCode((char.codePointAt(0) || 0) - 127365))
        .join('');
    return { ...c, iso };
}).sort((a, b) => a.name.localeCompare(b.name, 'fr'));
